# Site settings
title: 冥王星上的Tang
SEOTitle: Tang
header-img: img/photo-1506.jpg
email: breakfastpluto@qq.com
description: "一个散漫的人,一份闲散的事,此间少年不戴花"
keyword: "Tang,神秘学,塔罗,占星,瑜伽,宅,冥王星上的Tang,tang,TANG"
url: "https://tang-pluto.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'




# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Say Hello & Say Goodbye"
sidebar-avatar: /img/x2539883851.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# 
weibo_username:     tangpluto
github_username:    Tang-pluto



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8727238441c9f34acec9                            #生成的clientID
  clientSecret: b14b45c7b5ff5ef3cb5a84dbc0e9cf8918ac4b72    #生成的clientSecret
  repo: tang-pluto.github.io    #仓库名称
  owner: tang-pluto    #github用户名
  admin: tang-pluto
  distractionFreeMode: true #是否启用类似FB的阴影遮罩





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# More Sites
More Sites: [
    {
    title: "微信公众号：冥王星上的Tang",
        href: "https://mp.weixin.qq.com/s/zmonzmi7Dbu-Rg6IGVF7cw"
    },{
        title: "微信公众号：冥王星上的早餐",
        href: "https://mp.weixin.qq.com/s/fU3gXbBDB9wTC877DyT5BQ"
    },{
        title: "isha瑜伽",
        href: "https://isha.sadhguru.org/global/en"
  }
]
